### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by Torsten-K** [luckyshot/miki#6]
Everything works fine in version 3 so far, but I don’t know how to load a custom css file. In index.php there is a hint: _If you know CSS code, you can create a file called `customcss` to write your own custom CSS code_, but the link to it does not appear in the source code of the rendered files.

I tried custom.css, customcss.css and customcss, putting them into the Miki main directory and into the subdirectory where my files are stored, without success. Of course I could place a hard coded link to my CSS file in index.php on line 166, but what if I need different styles for different subdirectories? According to the version description, this should be able (_Custom per-folder CSS file_).

Any help is appreciated, thanks in advance.

**Comment by luckyshot** [comment]
Hi @Torsten-K 

I forgot to push some code changes to Miki. Try getting the latest version.

Then, create a new file `customcss` (http://example.com/miki/customcss/) and write the CSS inside:
```
html {background: black}
```

Hope this helps.

**Comment by Torsten-K** [comment]
Hi @luckyshot,

please forgive me for replying only after such a long time, but my email address had changed, and I had forgotten to change it here on Github, so I did not receive any messages.

Anyway, I installed the latest version, and now the customized CSS works like a charm. Thank you very much for your quick help!
