### ISSUE TITLE
After logging out can't get back in

### ISSUE THREAD

**Issue by tyeeman** [luckyshot/miki#9]
This is nice. I installed, made some edits, saw the logout link at the page bottom, clicked it, now I can't get back in to any page. I get this error - 

```
Notice: Undefined index: miki_auth_key in G:\Server\www\miki\index.php on line 270
```
Any tips to get back in?

**Comment by stbucher** [comment]
Open the URL pointing to the folder with the very long name again.

The folder name is essentially the login token, as I figured out myself.

Hope that helps.
